language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

install:
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements/test_26.txt; fi

script: nosetests --with-coverage

after_success:
    coveralls